module.exports = [
    {
        breed   : 'retriever-golden',
        weight    : '28kg',
        height : '54cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/kI4EbABtJQ0',
        description: 'The breed is friendly, gentle temperament means it is unsuited to being a professional guard dog, but its temperament has also made it the third-most popular family dog breed (by registration) in the United States,',
        history: 'The Golden Retriever originated in Scotland in the mid-19th century. At that time, wildfowl hunting was popular for the wealthy Scottish elite, but the existing retriever breeds were inadequate for retrieving downed game from both water and land.',
        one : 1,
        two : 1,
        three : 1,
        four : 1
    },
    {
        breed   : 'samoyed',
        weight    : '18kg',
        height : '50cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/YF8wvUqZfHs',
        description: 'Samoyed is a friendly disposition makes them poor guard dogs; an aggressive Samoyed is rare. The breed is characterized by an alert and happy expression which has earned the nicknames Sammie smile and smiley dog.',
        history: 'Samoyeds were originally used for hunting, herding reindeer, and hauling sledges for the Samoyede people in Siberia.  It takes its name from the Samoyedic peoples of Siberia.',
        one : 1,
        two : 1,
        three : 1,
        four : 1
    },
    {
        breed   : 'germanshepherd',
        weight    : '35kg',
        height : '62cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/M-uDiky1EKU',
        description: 'German Shepherds are moderately active dogs and are described in breed standards as self-assured. The breed is marked by a willingness to learn and an eagerness to have a purpose.',
        history: 'The German Shepherd is a relatively new breed of dog, with their origin dating to 1899. As part of the Herding Group, German Shepherds are working dogs developed originally for herding sheep. ',
        one : 1,
        two : 1,
        three : 1,
        four : 1
    },
    {
        breed   : 'pug',
        weight    : '7kg',
        height : '27cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/8Kkrmubsgf8',
        description: 'The Pug is a breed of dog with physically distinctive features of a wrinkly, short-muzzled face, and curled tail. The breed has a fine, glossy coat that comes in a variety of colours, most often fawn or black, and a compact square body with well-developed muscles.',
        history: 'Pugs were brought from China to Europe in the sixteenth century and were popularized in Western Europe by the House of Orange of the Netherlands, and the House of Stuart.',
        one : 2,
        two : 2,
        three : 2,
        four : 2
    },
    {
        breed   : 'corgi',
        weight    : '12kg',
        height : '27cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/95coGW386n8',
        description: 'Corgis have a very fun-loving personality. They are eager to please their owners in every possible way. Since the breed was bred to be a herding dog, they are very trainable and intelligent.',
        history: 'Welsh Corgis have historically been used as herding dogs, specifically for cattle. They are of the type of herding dog referred to as "heelers", meaning that they would nip at the heels of the larger animals to keep them on the move.',
        one : 2,
        two : 2,
        three : 2,
        four : 2
    },
    {
        breed   : 'husky',
        weight    : '23kg',
        height : '55cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/x2CaouIp1kE',
        description: 'The breed belongs to the Spitz genetic family. With proper training, they make great home pets and sled dogs.It is recognizable by its thickly furred double coat, erect triangular ears, and distinctive markings.',
        history: 'The Siberian Husky, Samoyed, and Alaskan Malamute are all breeds directly descended from the original sled dog. It is thought that the term "husky" is a corruption of the nickname "Esky" once applied to the Eskimo and subsequently to their dogs.',
        one : 2,
        two : 2,
        three : 2,
        four : 2
    },
    {
        breed   : 'collie-border',
        weight    : '17kg',
        height : '50cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/igy3zMfilFs',
        description: 'Considered highly intelligent, extremely energetic, acrobatic and athletic. They are often cited as the most intelligent of all domestic dogs.',
        history: 'Breed developed in the Anglo-Scottish border region for herding livestock, especially sheep. It was specifically bred for intelligence and obedience.',
        one : 3,
        two : 3,
        three : 3,
        four : 3
    },
    {
        breed   : 'beagle',
        weight    : '10kg',
        height : '37cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/BAf7lcYEXag',
        description: 'The beagle is intelligent but single-minded. It is a popular pet due to its size, good temper, and lack of inherited health problems.',
        history: 'Beagle was developed in Great Britain around the 1830s from several breeds, including the Talbot Hound, the North Country Beagle, the Southern Hound, and possibly the Harrier.',
        one : 3,
        two : 3,
        three : 3,
        four : 3
    },
    {
        breed   : 'mountain-bernese',
        weight    : '45kg',
        height : '65cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/X4mupT2AIsM',
        description: 'Bernese are outdoor dogs at heart, though well-behaved in the house; they need activity and exercise, but do not have a great deal of endurance. They can move with amazing bursts of speed for their size when motivated.',
        history: 'Historically, in some locales at least, the breed was called a Dürrbachhund.The breed was used as an all purpose farm dog for guarding property and to drive dairy cattle long distances from the farm to the alpine pastures.',
        one : 3,
        two : 3,
        three : 3,
        four : 3
    },
    {
        breed   : 'bulldog-boston',
        weight    : '7kg',
        height : '31cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/G3dWns5n21s',
        description: 'Bostons are small and compact with a short tail and erect ears. The AKC says they are highly intelligent and very easily trained. They are friendly and can be stubborn at times.',
        history: 'The Boston terrier breed originated around 1870, when Robert C. Hooper of Boston, purchased from Edward Burnett a dog named Judge (known later as Hoopers Judge), which was of a Bull and Terrier type lineage.',
        one : 4,
        two : 4,
        three : 4,
        four : 4
    },
    {
        breed   : 'dane-great',
        weight    : '70kg',
        height : '80cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/XXzZwEauNng',
        description: 'The Great Dane is an absolutely enormous German breed of domestic dog known for its giant size.The Great Dane is one of the laziest dog breeds: especially Delphi.',
        history: 'Large boarhounds resembling the Great Dane appear in ancient Greece, in frescoes from Tiryns dating back to the 14th–13th centuries BC.These large boarhounds continue to appear throughout ancient Greece in subsequent centuries up to the Hellenistic era',
        one : 4,
        two : 4,
        three : 4,
        four : 4
    },
    {
        breed   : 'hound-ibizan',
        weight    : '23kg',
        height : '36cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/jz1YAEPXhSU',
        description: 'Ibizan Hounds are intelligent, active, and engaging by nature. They are true "clowns" of the dog world, delighting in entertaining their people with their antics.',
        history: 'This breed originates in the island of Eivissa and has been traditionally used in the Catalan-speaking areas of Spain, and France where it was known under the name of le charnigue, to hunt rabbits and other small game.',
        one : 4,
        two : 4,
        three : 4,
        four : 4
    },
    {
        breed   : 'doberman',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/e00BzdF5LYA',
        description: 'The Dobermann is driven, strong and sometimes stubborn. Owning one requires commitment and care, but if trained well, they can be wonderful family dogs.',
        history: 'Dobermanns were first bred in the town of Apolda, in the German state of Thuringia around 1890, following the Franco-Prussian War by Karl Friedrich Louis Dobermann. Dobermann served in the dangerous role of local tax collector and ran the Apolda dog pound.',
        one : 1,
        two : 2,
        three : 3,
        four : 4
    },
    {
        breed   : 'basenji',
        weight    : '9.5kg',
        height : '40cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/tufBXaoUNM8',
        description: 'The Basenji is alert, energetic, curious and reserved with strangers. The Basenji tends to become emotionally attached to a single human. Basenjis dislike wet weather and can easily get over chain wire fences.',
        history: 'Originating on the continent of Africa, basenji-like dogs have lived with humans for thousands of years. Dogs resembling modern Basenjis, the Tesem, can be seen on stelae in the tombs of Egyptian pharaohs, sitting at the feet of their masters.',
        one : 1,
        two : 2,
        three : 3,
        four : 4
    },
    {
        breed   : 'bulldog-french',
        weight    : '11kg',
        height : '29cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/G3dWns5n21s',
        description: 'French Bulldogs make excellent companions.[9] The French Bulldog rarely barks, and if he does it is to draw attention, to point out that he needs something (like attention).',
        history: 'The origin of the modern French Bulldog breed descends directly from the dogs of the Molossians, an ancient Greek tribe. The dogs were spread throughout the ancient world by Phoenician traders. ',
        one : 1,
        two : 2,
        three : 3,
        four : 4
    },
    {
        breed   : 'whippet',
        weight    : '4.2kg',
        height : '35cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/oIJR9Naz-Hw',
        description: 'The Italian Greyhounds chest is deep, with a tucked up abdomen, long slender legs and a long neck that tapers down to a small head. The head is long and pointed, like a full sized greyhound. Overall, they look like miniature Greyhounds.',
        history: 'The name of the breed is a reference to the breeds popularity in Renaissance Italy. Mummified dogs very similar to the Italian Greyhound (or small Greyhounds) have been found in Egypt, and pictorials of small Greyhounds have been found in Pompeii, and they were probably the only accepted companion-dog there.',
        one : 4,
        two : 3,
        three : 2,
        four : 1
    },
    {
        breed   : 'hound-basset',
        weight    : '26kg',
        height : '34cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/pHJ8JRHAFlE',
        description: '',
        history: '',
        one : 4,
        two : 3,
        three : 2,
        four : 1
    },
    {
        breed   : 'dalmatian',
        weight    : '24kg',
        height : '58cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/NZm_i4t87kQ',
        description: '',
        history: '',
        one : 4,
        two : 3,
        three : 2,
        four : 1
    },
    {
        breed   : 'affenpinscher',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/ohnkNMFSnAc',
        description: 'They are active, adventurous, curious, and stubborn, but they are also fun-loving and playful. The breed is confident, lively, affectionate towards family members and is also very protective of them.',
        history: 'The breed is German in origin and dates back to the seventeenth century. The name is derived from the German Affe (ape, monkey). The breed predates and is ancestral to the Griffon Bruxellois (Brussels Griffon) and Miniature Schnauzer',
        one : 1,
        two : 1,
        three : 1,
        four : 4
    },
    {
        breed   : 'akita',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/KuHZbzvnX7g',
        description: 'The Akita is a powerful, independent and dominant breed, commonly aloof with strangers but affectionate with family members.',
        history: 'The Akita is a large breed of dog originating from the mountainous northern regions of Japan. Predecessors of the modern Akita were used for hunting bear, wild boar and deer in Japan as late as 1957.',
        one : 1,
        two : 1,
        three : 1,
        four : 4
    },
    {
        breed   : 'bullterrier-staffordshire',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/soOWhppnPD4',
        description: 'Staffies are known for its character of fearlessness. This, coupled with its affectionate nature, its off-duty quietness and trustworthy stability, make it a foremost all-purpose dog.',
        history: 'Before the 19th century, blood sports such as bull baiting, bear baiting and cock fighting were common. At the cattle market, dogs were set upon bulls,tenderising the meat but actually to provide entertainment for the crowd. ',
        one : 1,
        two : 1,
        three : 1,
        four : 4
    },
    {
        breed   : 'chihuahua',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/dHX2xul3WEk',
        description: 'He’s all dog, fully capable of competing in dog sports such as agility and obedience, and is among the top 10 watchdogs recommended by experts. He loves nothing more than being with his people and requires a minimum of grooming and exercise.',
        history: 'The Chihuahuas history is convoluted, and there are many theories surrounding the origin of the breed. Both folklore and archaeological finds show that the breed originated in Mexico.',
        one : 3,
        two : 4,
        three : 4,
        four : 3
    },
    {
        breed   : 'dachshund',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/1SaXch9bpXw',
        description: 'The standard size dachshund was developed to scent, chase, and flush out badgers and other burrow-dwelling animals, while the miniature dachshund was bred to hunt smaller prey. They were also used to track wounded deer and hunt prairie dogs.',
        history: 'The first verifiable references to the dachshund, originally named the "Dachs Kriecher" ("badger crawler") or "Dachs Krieger" ("badger warrior"), came from books written in the early 18th century',
        one : 3,
        two : 4,
        three : 4,
        four : 3
    },
    {
        breed   : 'mastiff-tibetan',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/BX0lvB3i9z4',
        description: 'They are intelligent and stubborn to a fault, so obedience training is recommended (although it is only mildly successful with some individuals) since this is a strong-willed, powerful breed.',
        history: 'In the early 20th century, King George V introduced a pair of Tibetan Mastiffs, and enough of the breed were available in England in 1906 to be shown at the Crystal Palace show. During war years, the breed lost favor and nearly died out in England.',
        one : 3,
        two : 4,
        three : 4,
        four : 3
    },
    {
        breed   : 'malamute',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/2UD18rNsRJI',
        description: 'Alaskan Malamutes are still in use as sled dogs for personal travel, hauling freight, or helping move light objects; some, however, are used for the recreational pursuit of sledding',
        history: 'The Malamute dog has had a distinguished history; aiding Rear Admiral Richard Byrd to the South Pole, and the miners who came to Alaska during the Gold Rush of 1896, as well as serving in World War II primarily as search and rescue dogs in Greenland,',
        one : 1,
        two : 3,
        three : 2,
        four : 4
    },
    {
        breed   : 'briard',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/cYvN_lRldH4',
        description: 'The Komondor is built for livestock guarding. The Komondors temperament is like that of most livestock guarding dogs; it is calm and steady when things are normal, but in case of trouble, the dog will fearlessly defend its charges',
        history: 'The Briard /briːɑːrd/  is an ancient breed of large herding dog, originally from France. A Briard-like dog appears in Gaston Febus Livre de chasse ("Book of the Hunt"), written in the late 14th century. ',
        one : 1,
        two : 3,
        three : 2,
        four : 4
    },
    {
        breed   : 'komondor',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/efeBXgQUJIY',
        description: 'Referred to as mop dogs, Komondor is a long-established powerful dog breed that has a natural guardian instinct to guard livestock and other property. Komondor was brought to Europe by the Cumans and the oldest known mention of it is in a Hungarian codex from 1544',
        history: 'Komondorok were brought to Hungary by Cumans, nomadic people who settled in Hungary during the 12th and 13th century. The name Komondor derives from Koman-dor, meaning "Cuman dog".',
        one : 1,
        two : 3,
        three : 2,
        four : 4
    },
    {
        breed   : 'leonberg',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/2-lpq0V02oU',
        description: 'The Leonberger is a giant dog breed. According to legend, the Leonberger was ostensibly bred as a symbolic dog that would mimic the lion in the town crest. It is in the Working Group for dog shows.',
        history: 'In the 1830s, Heinrich Essig, a dog breeder and mayor of the town of Leonberg, Germany, claimed to have created the Leonberger by crossing a female Landseer Newfoundland with a "barry" male from the Great St.',
        one : 3,
        two : 3,
        three : 3,
        four : 1
    },
    {
        breed   : 'wolfhound-irish',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/WkYvtVo2BO8',
        description: 'The breed is very old; there are suggestions it was brought to Ireland as early as 7000 BC. These dogs are mentioned in Irish literature which dates from the 5th century or, in the case of the Sagas, from the old Irish period.',
        history: 'Irish Wolfhounds have a varied range of personalities and are most often noted for personal quirks and individualism. An Irish Wolfhound is rarely mindless, and is rarely found to be destructive in the house.',
        one : 3,
        two : 3,
        three : 3,
        four : 1
    },
    {
        breed   : 'labrador',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/0cj81wHmfXc',
        description: 'Labradors are an intelligent breed with a good work ethic and generally good temperaments. Common working roles for Labradors include: hunting, disabled-assistance, and therapy work.',
        history: 'Modern Labradors ancestors originated on the island of Newfoundland. Founding breed of the Labrador was the St. Johns water dog,breed that emerged through ad-hoc breedings by early settlers of the island in the 16th century.',
        one : 3,
        two : 3,
        three : 3,
        four : 1
    },
    {
        breed   : 'eskimo',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/oljOjtq_V6w',
        description: 'They are not usually recommended for apartments, however they can live in apartments if well trained and properly exercised. Canadian Eskimo Dogs are very active indoors and do best with a fenced-in large yard. Because of their heavy coats, these dogs prefer cool climates.',
        history: 'Inuit never considered the dog as part of the animal kingdom (uumajuit), but merely as a tool for human existence.[13] It was, and still is (to a very limited extent), used by the Canadian Inuit as multi-purpose dogs, often put to work hunting seals and other Arctic game, and hauling supplies and people.',
        one : 2,
        two : 2,
        three : 2,
        four : 3
    },
    {
        breed   : 'pointer-german',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/I4FHYHUhyU0',
        description: 'This versatile sporting dog breed hunts many types of game, retrieves on land or from water, and is an affectionate companion. He has a striking, easy-care coat, but he needs plenty of vigorous exercise.',
        history: 'According to the American Kennel Club, it is likely that the GSP is descended from a breed known as the German Bird Dog, which itself is related to the Old Spanish Pointer introduced to Germany in the 17th century',
        one : 2,
        two : 2,
        three : 2,
        four : 3
    },
    {
        breed   : 'kelpie',
        weight    : '39kg',
        height : '67cm',
        avatar : '',
        youtube : 'https://www.youtube.com/embed/DDaBJOMdOsY',
        description: ' Australian sheep dog successful at mustering and droving with little or no guidance. It is a medium-sized dog and comes in a variety of colours. The Kelpie has been exported throughout the world and is used to muster livestock, primarily sheep, cattle and goats.',
        history: 'Kelpies are partly descended from Dingoes. At the time of the origin of the breed, it was illegal to keep dingoes as pets, some dingo owners registered their animals as Kelpies or Kelpie crosses.',
        one : 2,
        two : 2,
        three : 2,
        four : 3
    },
];
